# Generated by Django 4.0 on 2021-12-11 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('route', models.CharField(max_length=180)),
                ('password', models.CharField(max_length=64)),
                ('content', models.TextField()),
            ],
        ),
    ]
