# Generated by Django 4.0 on 2021-12-16 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='password',
            field=models.CharField(max_length=256),
        ),
    ]
